name: Auto Update Customs Rates

on:
  schedule:
    - cron: '0 */6 * * *' # اجرا هر ۶ ساعت یک‌بار
  workflow_dispatch: # فعال کردن دکمه اجرای دستی

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    # دادن دسترسی به بات برای نوشتن فایل در مخزن
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper Script
        run: python scraper.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add rates.json
          # اگر تغییری در نرخ‌ها نبود، ارور نده و خارج شو
          git commit -m "🤖 Update exchange rates automatically" || exit 0
          git push
